import { BrandRecord } from "redux/operationalMetrics/types";


export const fakeTable: BrandRecord[] = [
    {
        brandId: 1,
        brandName: "Test Brand",
        year: 2022,
        month: 12,
        monthName: "Diciembre",
        score: 4.3,
        delay: 20,
        cancellation: 10,
        availability: 75,
        isZombie: false,
        productAvailability: 90
    },
    {
        brandId: 1,
        brandName: "Test Brand",
        year: 2022,
        month: 11,
        monthName: "Noviembre",
        score: 4.0,
        delay: 21,
        cancellation: 13,
        availability: 75,
        isZombie: false,
        productAvailability: 84
    },
    {
        brandId: 1,
        brandName: "Test Brand",
        year: 2022,
        month: 10,
        monthName: "Octubre",
        score: 3.6,
        delay: 23,
        cancellation: 12,
        availability: 80,
        isZombie: false,
        productAvailability: 68
    },
    {
        brandId: 1,
        brandName: "Test Brand",
        year: 2022,
        month: 11,
        monthName: "Septiembre",
        score: 3.9,
        delay: 22,
        cancellation: 15,
        availability: 78,
        isZombie: false,
        productAvailability: 77
    },
    {
        brandId: 1,
        brandName: "Test Brand",
        year: 2021,
        month: 10,
        monthName: "Octubre",
        score: 4.6,
        delay: 15,
        cancellation: 5,
        availability: 95,
        isZombie: false,
        productAvailability: 95
    },
    {
        brandId: 1,
        brandName: "Test Brand",
        year: 2021,
        month: 3,
        monthName: "Marzo",
        score: 2.2,
        delay: 25,
        cancellation: 16,
        availability: 85,
        isZombie: false,
        productAvailability: 94
    },
    {
        brandId: 1,
        brandName: "Test Brand",
        year: 2021,
        month: 11,
        monthName: "Noviembre",
        score: 4.3,
        delay: 20,
        cancellation: 10,
        availability: 75,
        isZombie: false,
        productAvailability: 91
    },
    {
        brandId: 1,
        brandName: "Abocados",
        year: 2020,
        month: 12,
        monthName: "Diciembre",
        score: 4.3,
        delay: 20,
        cancellation: 10,
        availability: 75,
        isZombie: false,
        productAvailability: 89
    },
    {
        brandId: 1,
        brandName: "Buenas Papas",
        year: 2020,
        month: 12,
        monthName: "Diciembre",
        score: 4.3,
        delay: 20,
        cancellation: 10,
        availability: 75,
        isZombie: false,
        productAvailability: 89
    },
    {
        brandId: 1,
        brandName: "Carmela",
        year: 2020,
        month: 12,
        monthName: "Diciembre",
        score: 4.3,
        delay: 20,
        cancellation: 10,
        availability: 75,
        isZombie: false,
        productAvailability: 89
    },
    {
        brandId: 1,
        brandName: "Zippy",
        year: 2020,
        month: 12,
        monthName: "Diciembre",
        score: 4.3,
        delay: 20,
        cancellation: 10,
        availability: 75,
        isZombie: false,
        productAvailability: 89
    },
]